server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/choibaemin_db
    username: root
    password: 1111
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20

  jpa:
   show-sql: true
   hibernate:
    ddl-auto: validate
